# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: medficientsam-reproduce

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.*
  - torchvision=0.17.2
  - lightning=2.2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - timm=0.*
  - monai=1.*
  - opencv=4.9.0
  - openvino=2024.0.0

  # --------- loggers --------- #
  - wandb